# Generated by Django 4.1.1 on 2022-09-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeeksModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("desciption", models.TextField()),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
